server:
  port: 8880
  servlet:
    context-path: /

spring:
  config:
    activate:
      on-profile: dev
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    mvc:
      static-path-pattern: /static/**

mybatis:
  mapper-locations: /mappers/*.xml, /mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info

model:
  tank:
    dir: D:/dev_etc/laos/
    template: D:/dev_etc/laos/tank/templates/
    paramModel: D:/dev_etc/laos/tank/SMTankSim.exe
  fard:
    dir: D:/dev_etc/laos/fard/
    result: D:/dev_etc/laos/fard/Result/
    model: D:/dev_etc/laos/fard/Main_Fard.exe
  dmh:
    dir: D:\SON\2023\00.DATA\dmh\
    folders: Evaporation,Rainfall,Water Level