server:
  port: 8000
  servlet:
    context-path: /

spring:
  datasource:
    hikari:
#      jdbc-url: jdbc:log4jdbc:postgresql://192.168.0.6:5432/laos
#      username: laos
#      password: laos00
      jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/laos_test
      username: postgres
      password: postgres00
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    mvc:
      static-path-pattern: /static/**

mybatis:
  mapper-locations: /mappers/*.xml, /mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info