server:
  port: 8000
  servlet:
    context-path: /

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/laos_test
      username: postgres
      password: postgres00
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true

mybatis:
  mapper-locations: /mappers/*.xml, /mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info